#!/usr/bin/env bash

# Get the script directory
MODULE_PARENT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Check if venv exists, and create if not
VENV_DIR="${MODULE_PARENT}/venv"
if [[ ! -d "$VENV_DIR" ]]; then
    echo "No venv detected, creating one and installing dependencies!"
    python -m venv "${VENV_DIR}"
    source "${VENV_DIR}/bin/activate"
    pip install -r requirements.txt
else
    source "${VENV_DIR}/bin/activate"
fi

# And run the script
PYTHONPATH="$PYTHONPATH:$MODULE_PARENT" python -m trace_to_goal ${@:1}
